perfix: 
  text: '&e服务器 &d&l>> &r&a'
  json: '"text":"\u00a7e服务器 \u00a7d\u00a7l>> \u00a7r\u00a7a","hoverEvent":{"action":"show_text","contents":{"text":"服务器管理系统 版本 0.0.5\n如遇到bug请及时反馈。","color":"green"}},"clickEvent":{"action":"suggest_command","value":"/servermanager"}'

debugMsg: 
  perfix: '[ServerManager] '
  info:
    active: true
    onPluginEnable: '插件 "Server Manager" 已成功启用'
    onPluginDisable: '插件 "Server Manager" 已成功停用'
    announcementCd: '通知项目 [#1] 将在 #2 ticks 之后再次显示'
    chatTriggerInfo: '玩家 [#1] 发送的消息 [#2] 触发了正则表达式 [#3]'
  warn:
    active: true
    announcementOverflow: '同一时刻显示通知的数量过多'
    announcementCircle: '一个list种类的通知正试图触发它自己'
  error: 
    active: true
    printStacktrace: true
    commandInitError: '无法注册所有的指令。因为这些指令没有全部在 plugin.yml 文件里注册'
    deathMessageError: '无法播报一个实体的死亡信息'
    biomeMessageError: '无法播报一个玩家所处的生物群系'
    entityCountError: '无法控制服务器的实体数量'
    shootMessageError: '无法将射中生物的消息播报给玩家'
    playerDeathError: '无法获取玩家的死亡坐标'
    idleTimeoutError: '无法获取玩家的挂机时长'
    surroundMessageError: '无法获取正在攻击玩家的生物'
    announcementError: '无法播报通知'
    playerChatError: '无法检查玩家发送的消息'

command: 
  broadcast: 
    active: true
    messagePerfix: true
    lessArgsMsg: '使用方法: /servermanager broadcast <where> <...> 播报一条消息'
    wrongArgMsg: 'Unknown places to be displayed.'

    bossbar: 
      active: true
      messagePerfix: true
      bossbarPerfix: false
      lessArgsMsg: '使用方法 /servermanager broadcast bossbar <显示时长tick数> <有无前缀> <是否强制显示> <消息内容> 显示boss栏消息'
      wrongTick: '<显示时长tick数> 无效的持续时间参数。请输入一个整数。'
      wrongBoolean: '<有无前缀> 和 <是否强制显示> 参数必须为true或false'
      noPermissionMsg: '你没有使用这个指令的权限'
      successMsg: '成功的在 bossbar 广播了一条消息'
      successClearMsg: '已清除正在进行的 bossbar 消息'
      failMsg: '无法广播消息。可能是因为有其它正在显示的消息。'
      failClearMsg: '当前没有可以清除的 bossbar 消息'

    chat:
      active: true
      messagePerfix: true
      lessArgsMsg: '使用方法 /servermanager broadcast chat <消息内容> 显示聊天消息'
      noPermissionMsg: '你没有使用这个指令的权限'

  home:
    active: true
    messagePerfix: true
    lessArgsMsg: '使用方法 /servermanager home <操作> <名称> 设置传送点'
    wrongArgMsg: '未知的 home 操作'
    wrongSenderMsg: '这个指令只能由玩家执行'
    noPermissionMsg: '你没有使用这个指令的权限'
    duplicatedHome: '重复的 home 名称'
    undefinedHome: '未知的 home 名称'
    emptyHomeList: '当前没有设置任何 home'
    successAddMsg: '成功设置 #1 传送点'
    successSetMsg: '成功修改 #1 传送点'
    successRemoveMsg: '成功移除 #1 传送点'
    successListMsg: '当前已设置的 home 的列表:'
    successGetMsg: '#1 位于世界 #2 的 [#3, #4, #5] 处，生物群系为 #6'
    successShareMsg: '#1 分享了自己的 #2 传送点，位于世界 #3 的 [#4, #5, #6] 处，生物群系为 #7'
    successTpMsg: '成功传送到 #1 传送点'

  back:
    active: true
    messagePerfix: true
    noPermissionMsg: '你没有使用这个指令的权限'
    wrongSenderMsg: '这个指令只能由玩家执行'
    noLastLocationMsg: '没有上次所在的地方'
    successMsg: '已返回世界 #1 的 [#2, #3, #4] 处，生物群系为 #5'

announcement:
  bossbarExample:
    type: 'bossbar'
    forceShow: true
    perfix: true
    exitTime: 600
    cooldownMin: 6000
    cooldownMax: 12000
    text: '测试用的bossbar通知'
  chatExample:
    type: 'chat'
    perfix: true
    cooldownMin: 6000
    cooldownMax: 12000
    text: '测试用的聊天栏通知'
  commandExample:
    type: 'command'
    cooldownMin: 6000
    cooldownMax: 12000
    text: 'tellraw @a "测试用的指令通知"'
  listTest:
    type: 'chat'
    perfix: 'true'
    cooldownMin: 6000
    cooldownMax: 12000
    text: '测试和用的列表通知'
  listExample:
    type: 'list'
    cooldownMin: 6000
    cooldownMax: 12000
    ignoreCooldown: true
    resetCooldown: false
    list:
    - 'listTest'
    - 'bossbarExample'
    - 'chatExample'
    - 'commandExample'

chatTrigger:
  example:
    regexList: 
    - 'fuck'
    - 'bitch'
    - 'shit'
    isCancel: false
    isReplace: true
    replacement: '***'
    hasAction: false
  eg:
    regexList:
    - 'bug'
    isCancel: false
    isReplace: false
    hasAction: true
    actionCmdList:
    - 'tellraw @a "&e服务器 &d&l>> &r&a可以向我们反馈遇到的bug哦"'
  fuck:
    regexList:
    - '垃.*圾.*服.*务.*器'
    isCancel: true
    hasAction: true
    actionCmdList:
    - 'tellraw #1 "&e服务器 &d&l>> &r&a请注意素质。谢谢。"'

function:
  announcement:
    active: false
    maxStack: 10
    list:
    - 'bossbarExample'
    - 'chatExample'
    - 'commandExample'
    - 'listExample'
  chatTrigger:
    active: true
    list:
    - 'example'
    - 'eg'
    - 'fuck'
  mobDeathMessage:
    bossbarPerfix: true
    messagePerfix: true
    active: true
    exitTime: 60
    healthLimit: 150.5
    reason:
      noReason: '#1 死了'
      unknownReason: 
        a: '#1 被杀死了'
        b: '#1 被 #2 杀死了'
        c: '#1 在与 #3 的战斗中被杀'
        d: '#1 在与 #3 的战斗中被 #2 杀死了'
      blockExplosion: 
        a: '#1 爆炸了'
        b: '#1 被 #2 炸死了'
        c: '#1 在与 #3 的战斗中爆炸了'
        d: '#1 在与 #3 的战斗中被 #2 炸死了'
      contact: 
        a: '#1 被戳死了'
        b: '#1 被 #2 戳死了'
        c: '#1 在与 #3 的战斗被戳死了'
        d: '#1 在与 #3 的战斗中被 #2 戳死了'
      cramming: 
        a: '#1 因过度挤压而死'
        b: '#1 被 #2 挤扁了'
        c: '#1 在与 #3 的战斗因过度挤压而死'
        d: '#1 在与 #3 的战斗中被 #2 挤扁了'
      custom: 
        a: '#1 死了'
        b: '#1 被 #2 打死了'
        c: '#1 在与 #3 的战斗中死了'
        d: '#1 在与 #3 的战斗中被 #2 打死了'
      dragonBreath: 
        a: '#1 被龙息烤熟了'
        b: '#1 被 #2 的龙息烤熟了'
        c: '#1 在与 #3 的战斗中被龙息烤熟了'
        d: '#1 在与 #3 的战斗中被 #2 的龙息烤熟了'
      drowing: 
        a: '#1 淹死了'
        b: '#1 被 #2 淹死了'
        c: '#1 在试图逃离 #3 时淹死了'
        d: '#1 在试图逃离 #3 时被 #2 淹死了'
      dryout: 
        a: '#1 脱水了'
        b: '#1 被 #2 榨干了'
        c: '#1 在试图逃离 #3 时脱水而死'
        d: '#1 在试图逃离 #3 时被 #2 榨干了'
      entityAttack: 
        a: '#1 被杀死了'
        b: '#1 被 #2 杀死了'
        c: '#1 在试图逃离 #3 时被杀死了'
        d: '#1 在试图逃离 #3 时被 #2 杀死了'
      entityExplosion: 
        a: '#1 爆炸了'
        b: '#1 被 #2 炸死了'
        c: '#1 在试图逃离 #3 时爆炸了'
        d: '#1 在试图逃离 #3 时被 #2 炸死了'
      entitySweepAttack:
        a: '#1 被误杀了'
        b: '#1 被 #2 误杀了'
        c: '#1 在试图逃离 #3 时被误杀了'
        d: '#1 在试图逃离 #3 时被 #2 误杀了'
      fall:
        a: '#1 从高处摔了下来'
        b: '#1 被 #2 击落'
        c: '#1 因为 #3 注定要摔死'
        d: '#1 在试图逃离 #3 时被 #2 击落'
      fallingBlock:
        a: '#1 被压扁了'
        b: '#1 被 #2 压扁了'
        c: '#1 在与 #3 战斗时被压扁了'
        d: '#1 在与 #3 战斗时被 #2 压扁了'
      fire: 
        a: '#1 浴火焚身'
        b: '#1 被 #2 烤熟了'
        c: '#1 在与 #3 战斗时走入了火中'
        d: '#1 在与 #3 战斗时被 #2 烤熟了'
      fireTick:
        a: '#1 被烧死了'
        b: '#1 被 #2 烧死了'
        c: '#1 在与 #3 战斗时被烤得酥脆'
        d: '#1 在与 #3 战斗时被 #2 烧死了'
      flyIntoWall:
        a: '#1 感受到了动能'
        b: '#1 被 #2 撞死了'
        c: '#1 在试图逃离 #3 时感受到了动能'
        d: '#1 在试图逃离 #3 时被 #2 撞死了'
      freeze:
        a: '#1 冻死了'
        b: '#1 被 #2 冻死了'
        c: '#1 在与 #3 战斗时被冻死了'
        d: '#1 在与 #3 战斗时被 #2 冻死了'
      hotFloor:
        a: '#1 发现了地板是岩浆'
        b: '#1 被 #2 烫死了'
        c: '#1 因 #3 而步入危险之地'
        d: '#1 在与 #3 战斗时被 #2 烫死了'
      lava:
        a: '#1 试图在岩浆里游泳'
        b: '#1 被 #2 化成灰烬'
        c: '#1 在逃离 #3 时试图在岩浆里游泳'
        d: '#1 在与 #3 战斗时被 #2 化成灰烬'
      lightning:
        a: '#1 被闪电击中'
        b: '#1 被 #2 电死了'
        c: '#1 在与 #3 战斗时被闪电击中'
        d: '#1 在与 #3 战斗时被 #2 电死了'
      magic:
        a: '#1 被魔法杀死了'
        b: '#1 被 #2 使用的魔法杀死了'
        c: '#1 在试图逃离 #3 时被魔法杀死了'
        d: '#1 在试图逃离 #3 时被 #2 使用的魔法杀死了'
      melting:
        a: '#1 融化了'
        b: '#1 被 #2 融化了'
        c: '#1 在与 #3 战斗时融化了'
        d: '#1 在与 #3 战斗时被 #2 融化了'
      poison:
        a: '#1 中毒身亡'
        b: '#1 被 #2 毒死了'
        c: '#1 在试图逃离 #3 时中毒身亡'
        d: '#1 在试图逃离 #3 时被 #2 毒死了'
      projectile:
        a: '#1 中箭而亡'
        b: '#1 被 #2 击中'
        c: '#1 在与 #3 战斗时中箭而亡'
        d: '#1 在与 #3 战斗时被 #2 射杀'
      sonicBoom:
        a: '#1 被一道音波尖啸抹除了'
        b: '#1 被 #2 抹除了'
        c: '#1 在试图逃离 #3 时被一道音波尖啸抹除了'
        d: '#1 在试图逃离 #3 时被 #2 抹除了'
      starvation:
        a: '#1 饿死了'
        b: '#1 被 #2 饿死了'
        c: '#1 在与 #3 战斗时饿死了'
        d: '#1 在与 #3 战斗时被 #2 饿死了'
      suffocation:
        a: '#1 在墙里窒息而亡'
        b: '#1 被 #2 塞进了石头缝里'
        c: '#1 在与 #3 战斗时在墙里窒息而亡'
        d: '#1 在与 #3 战斗时被 #2 塞进了石头缝里'
      suicide:
        a: '#1 自杀了'
        b: '#1 在与 #2 战斗时自杀了'
        c: '#1 向 #3 投降了'
        d: '#1 在向 #3 投降时因 #2 而自杀了'
      thorns:
        a: '#1 被反伤致死'
        b: '#1 在试图伤害 #2 时被杀'
        c: '#1 在与 #3 战斗时被反伤致死'
        d: '#1 在与 #3 战斗时被 #2 反伤致死'
      void:
        a: '#1 掉出了这个世界'
        b: '#1 被 #2 扔出了这个世界'
        c: '#1 与 #3 不共戴天'
        d: '#1 在与 #3 战斗时被 #2 扔出了这个世界'
      wither:
        a: '#1 凋谢了'
        b: '#1 被 #2 凋零'
        c: '#1 在与 #3 战斗时凋谢了'
        d: '#1 在与 #3 战斗时被 #2 凋零'
  biomeChangeMsg:
    bossbarPerfix: true
    active: true
    exitTime: 40
    message: '#1 进入了生物群系 #2'
  entityLimit:
    bossbarPerfix: true
    activeBroadcast: true
    activeWarn: true
    activeClear: false
    broadcastCD: 36000
    broadcastTime: 200
    forceBroadcast: false
    warnLevel: 1000
    forceWarn: true
    clearLevel: 2000
    clearTime: 1200
    forceClear: true
    clearPerfix: true
    broadcastMsg: '当前世界总共有 #1 个实体'
    warnMsg: '当前世界总共有 #1 个实体，请注意清理'
    clearMsg: '当前世界总共有 #1 个实体，部分实体将在 #2 秒后清除'
    clearBroadcast: '清除了 #1 个物品'
  shootMessage:
    active: true
    broadcastToAll: false
    bossbarPerfix: true
    exitTime: 100
    forceShow: false
    message: '#1 射中了 #2 还剩 #3 生命值'
  playerDeathMessage:
    active: true
    broadcastToAll: true
    hasPerfix: true
    message: '#1 的死亡地点位于世界 #2 的 [#3, #4, #5] 处'
  playerIdleTimeout:
    active: true
    idleLimit: 6000
    kick: false
    messagePerfix: true
    kickPerfix: true
    idleMessage: '#1 暂时离开了'
    backMessage: '#1 回来了。总计离开 #2 秒'
    kickMessage: '疑似挂机'
  surroundMessage:
    active: true
    monsterCount: 8
    monsterDistance: 10.5
    hurtFrequency: 50
    bossbarPerfix: true
    exitTime: 200
    forceShow: false
    message: '#1 正在受到 #2 等 #3 个怪物的围攻'

